version: '2'
services:
    ssjk:
        restart: unless-stopped
        volumes:
            - '/mnt:/mnt' #映射你需要的目录
            - ./config:/app/config
            - ./logs:/app/logs
        ports:
            - '5432:5432'
        environment: #群晖下id好像不可用，自行注释掉使用
            - PUID=0
            - PGID=0
            - UMASK=022
        container_name: ssjk
        network_mode: bridge
        image: 'chaslllll/ssjk:latest'
