name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 设置环境变量以包含时间戳  
      - name: Get current date  
        run: echo "BUILD_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV  
  
      # 构建并推送 Docker 镜像  
      - name: Build and push Docker images  
        uses: docker/build-push-action@v3  
        with:  
          context: .  
          push: true  
          tags: |  
            ${{ secrets.DOCKER_USERNAME }}/ssjk:latest  
            ${{ secrets.DOCKER_USERNAME }}/ssjk:${{ env.BUILD_DATE }}
